version: "3.8"
services:
  amorattar:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amorattar
    restart: unless-stopped
    ports:
      - "3002:3002"
    env_file:
      - .env
      
