version: "3.8"
services:
  amorattar:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amorattar
    restart: unless-stopped
    ports:
      - "3002:3002"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    env_file:
      - .env
      
